### ISSUE TITLE
SchemaGenerationError: Could not find matching type for object

### ISSUE THREAD

**Issue by nigotiator** [asyrjasalo/RESTinstance#37]
This very simple GET test fails in Windows10 (Python 2.7.15) but it works with Ubuntu 16.04 (Python 2.7.12).
Fails in Windows with ` SchemaGenerationError: Could not find matching type for object: 1536489510350L`

Test was run in virtualenv  in both systems and following packages were only installed by pip:
* RESTinstance
* robotframework

Test uses Liikennevirasto's open api to get the vessel location --> Can be easily tested with Curl or with browser: 
`curl -X GET --header 'Accept: application/json' 'https://meri.digitraffic.fi/api/v1/locations/latest/230629000' `

Test case:
```
*** Settings ***
Library           REST    https://meri.digitraffic.fi

*** Test Cases ***
Get
    Set Headers    {"Accept":"application/json;charset=UTF-8","User-Agent":"curl/7.47.0"}
    REST.Get    /api/v1/locations/latest/230181000    validate=true
```

Traceback:
```
Traceback (most recent call last):
  File "C:\temp\testi\lib\site-packages\REST\keywords.py", line 145, in get
    return self._request(endpoint, request, validate)['response']
  File "C:\temp\testi\lib\site-packages\REST\keywords.py", line 494, in _request
    instance = self._instantiate(request, response, validate)
  File "C:\temp\testi\lib\site-packages\REST\keywords.py", line 517, in _instantiate
    schema['response']['body'] = self._new_schema(response['body'])
  File "C:\temp\testi\lib\site-packages\REST\keywords.py", line 553, in _new_schema
    builder.add_object(value)
  File "C:\temp\testi\lib\site-packages\genson\schema\builder.py", line 64, in add_object
    self._root_node.add_object(obj)
  File "C:\temp\testi\lib\site-packages\genson\schema\node.py", line 50, in add_object
    schema_generator.add_object(obj)
  File "C:\temp\testi\lib\site-packages\genson\schema\generators\object.py", line 56, in add_object
    self._properties[prop].add_object(subobj)
  File "C:\temp\testi\lib\site-packages\genson\schema\node.py", line 50, in add_object
    schema_generator.add_object(obj)
  File "C:\temp\testi\lib\site-packages\genson\schema\generators\array.py", line 42, in add_object
    self._items.add_object(item)
  File "C:\temp\testi\lib\site-packages\genson\schema\node.py", line 50, in add_object
    schema_generator.add_object(obj)
  File "C:\temp\testi\lib\site-packages\genson\schema\generators\object.py", line 56, in add_object
    self._properties[prop].add_object(subobj)
  File "C:\temp\testi\lib\site-packages\genson\schema\node.py", line 50, in add_object
    schema_generator.add_object(obj)
  File "C:\temp\testi\lib\site-packages\genson\schema\generators\object.py", line 56, in add_object
    self._properties[prop].add_object(subobj)
  File "C:\temp\testi\lib\site-packages\genson\schema\node.py", line 49, in add_object
    schema_generator = self._get_generator_for_object(obj)
  File "C:\temp\testi\lib\site-packages\genson\schema\node.py", line 114, in _get_generator_for_object
    return self._get_generator_for_('object', obj)
  File "C:\temp\testi\lib\site-packages\genson\schema\node.py", line 146, in _get_generator_for_
    kind, schema_or_obj))
```

**Comment by hidebear** [comment]
I got this problem too, 
it's occurred in Win 10 (Python 2.7.15 and robot  3.0.4) and Win7 (Python 2.7.13 and robot 3.0.4).
But there's no such issue in Fedora (Python 2.7.15 and robot 3.0.4).

**Comment by asyrjasalo** [comment]
@hidebear: Using Python 2 (over 3) is a workaround, not a solution.

Anyway, I am interested in the problem so I'll see if I can reproduce this on Windows 10.

**Comment by asyrjasalo** [comment]
Could not reproduce.

**Comment by kanchi240** [comment]
This problem probably caused by when the number field value in the response is exceed the range of the `sys.maxint` value when using python2, everything is ok after upgrade to python 3.

**Comment by iamdhruvanand** [comment]
This workaround works with which exact versions of python and robot please?

**Comment by kanchi240** [comment]
@iamdhruvanand 
update to the newest python3.
