### ISSUE TITLE
Error when attempting to run ./tests on Fedora 27

### ISSUE THREAD

**Issue by jjwong** [asyrjasalo/RESTinstance#8]
I get error below when I try to run the default tests.

```
Successfully built 6e24adbcd6c5
chown: /home/robot/results: Permission denied
chown: /home/robot/tests: Permission denied
[ ERROR ] Unexpected error: PermissionError: [Errno 13] Permission denied: '/home/robot/tests'
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/robot/utils/application.py", line 83, in _execute
    rc = self.main(arguments, **options)
  File "/usr/local/lib/python3.6/site-packages/robot/run.py", line 439, in main
    settings['Extension']).build(*datasources)
  File "/usr/local/lib/python3.6/site-packages/robot/running/builder.py", line 70, in build
    return self._parse_and_build(paths[0])
  File "/usr/local/lib/python3.6/site-packages/robot/running/builder.py", line 77, in _parse_and_build
    suite = self._build_suite(self._parse(path))
  File "/usr/local/lib/python3.6/site-packages/robot/running/builder.py", line 86, in _parse
    extensions=self.extensions)
  File "/usr/local/lib/python3.6/site-packages/robot/parsing/model.py", line 47, in TestData
    extensions)
  File "/usr/local/lib/python3.6/site-packages/robot/parsing/model.py", line 227, in populate
    warn_on_skipped, extensions, recurse)
  File "/usr/local/lib/python3.6/site-packages/robot/parsing/populators.py", line 112, in populate
    include_suites)
  File "/usr/local/lib/python3.6/site-packages/robot/parsing/populators.py", line 167, in _get_children
    incl_suites):
  File "/usr/local/lib/python3.6/site-packages/robot/parsing/populators.py", line 179, in _list_dir
    names = os.listdir(unic(dir_path))

```

**Comment by jjwong** [comment]
I have a workaround in this PR https://github.com/asyrjasalo/RESTinstance/pull/9

**Comment by asyrjasalo** [comment]
The PR solution works (which is running Docker as `--privileged`) but researching if this could be resolved with "slightly softer measures". Thanks for bringing this out!

**Comment by asyrjasalo** [comment]
Help wanted from Docker and Fedora (or any SELinux enabled-by-default distro) users: What are the minimum rights we need to pass to `docker run` to make this work, without running in privileged mode?

Note to self, that would be beneficial to have this library built and tested in CI at least with Ubuntu, Fedora and CentOS, but I have little time to get this done in the near future.

**Comment by jjwong** [comment]
No longer needed. No longer using Fedora.
